language: ruby
os: linux
dist: bionic

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: focal

before_install: skip

install:
  - curl -o- https://raw.githubusercontent.com/Maverobot/dot-spacemacs/${TRAVIS_BRANCH}/installer.sh | tee /dev/tty | bash

script: skip

after_success: skip
