name: CI

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  installer-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache the spacemacs repository folder
        uses: actions/cache@v4.0.0
        with:
          path: ~/.emacs.d
          key: saved-emacs-d-${{ matrix.os }}

      - name: Create a placeholder folder for org-roam
        run: mkdir ~/org/home/roam -p

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Install everything needed for the spacemacs config
        run: ./installer.sh ${{ steps.branch-name.outputs.current_branch }}
        shell: bash

      - name: Copy the generated index.html to the checked out repo path
        run: |
          mkdir ~/work/dot-spacemacs/dot-spacemacs/public
          cp ~/.spacemacs.d/docs/index.html ~/work/dot-spacemacs/dot-spacemacs/public

      - name: GitHub Pages
        if: matrix.os == 'ubuntu-20.04' && success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
